# Application Name
spring:
  application:
    name: yallatawsil-backend

# Port number
server:
  port:8080

# Apis
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operations-sorter: method
    tags-sorter: alpha

# Logs
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.data: INFO
    com.yallatawsil.backend: DEBUG


ai:
  deepseek:
    api-key: ${DEEPSEEK_API_KEY}
    chat:
      options:
        model: deepseek-chat
  optimizer:
    enabled: true
    history-days: 90
    min-history-records: 10


tour:
  optimizer:
    algorithm: NEAREST_NEIGHBOR
